<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Jellyfin.Plugin.KidsMode</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.KidsMode</AssemblyName>
    <Version>0.1.0.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinControllerVersion)" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Web\kidsMode.js" />
  </ItemGroup>

</Project>
