<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Jellyfin.Plugin.ArtworkRefresher</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.ArtworkRefresher</AssemblyName>
    <Version>1.0.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinControllerVersion)" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Web\artworkRefresher.js" />
  </ItemGroup>

</Project>
