<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Jellyfin.Plugin.DiscoverHome</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.DiscoverHome</AssemblyName>
    <Version>0.1.0.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinControllerVersion)" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Web\discoverHome.js" />
    <EmbeddedResource Include="Web\discoverHome.css" />
  </ItemGroup>

</Project>
